---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: trailing-whitespace
          - id: check-toml
          # - id: pretty-format-json
          #   args:
          #       - --autofix
    # - repo: https://github.com/adrienverge/yamllint.git
    #   rev: v1.21.0
    #   hooks:
    #       - id: yamllint
    #         args:
    #             - --format
    #             - parsable
    #             - --strict
    #             - '-d {extends: relaxed, rules: {line-length: {max: 150}}}'

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11
      hooks:
          - id: yamlfmt
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
            files: (src|tests).*py
    - repo: https://github.com/PyCQA/isort
      rev: 5.6.4
      hooks:
          - id: isort
            args: [-m, '3', --tc]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.2.1
      hooks:
          - id: prettier
            types:
                - ts
    - repo: local
      hooks:
          - id: pyright
            name: pyright
            entry: bash -c 'cd python-cli && poetry run pyright'
            language: node
            pass_filenames: false
            types: [python]
            additional_dependencies: [pyright@1.1.91]
    - repo: local
      hooks:
          - id: tsc-lint
            name: tsc-lint
            entry: bash -c 'yarn compile && yarn lint --fix'
            language: node
            pass_filenames: false
            types:
                - ts
