---
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    pytest:
        defaults:
            run:
                working-directory: python-cli

        timeout-minutes: 20
        strategy:
            fail-fast: false
            matrix:
                cfg:
                    - os: ubuntu-latest
                      python-version: '3.6'
                    # - os: ubuntu-latest
                    #   python-version: '3.7'
                    # - os: ubuntu-latest
                    #   python-version: '3.8'
                    # - os: ubuntu-latest
                    #   python-version: '3.9'
                    # - os: macos-latest
                    #   python-version: '3.6'
                    # - os: macos-latest
                    #   python-version: '3.7'
                    # - os: macos-latest
                    #   python-version: '3.8'
                    # - os: macos-latest
                    #   python-version: '3.9'

        runs-on: ${{ matrix.cfg.os }}
        steps:
            - uses: actions/checkout@v2
            - run: printenv
            - run: cat $GITHUB_EVENT_PATH
            - run: cat /home/runner/work/_temp/_runner_file_commands/set_env_ea021ccd-5cb5-43a7-b019-38de4b586b5c
            - run: cat $GITHUB_ENV
            - run: cat $XDG_CONFIG_HOME
            # - uses: actions/setup-python@v2
            #   with:
            #       python-version: ${{ matrix.cfg.python-version }}
            # - run: pip install poetry
            # - run: poetry config virtualenvs.in-project true
            # - run: poetry install
            # - uses: pre-commit/action@v2.0.0
            #   with:
            #       extra_args: --verbose --all-files

            # - run: |
            #       pwd;ls -la;
            #       poetry run python -m get_flakes.server &
            #       sleep 1
            #       poetry run pytest -m 'not flakysim'
